// TODO: Create a function that returns a license badge based on which license is passed in
// If there is no license, return an empty string
function renderLicenseBadge(license) {}

// TODO: Create a function that returns the license link
// If there is no license, return an empty string
function renderLicenseLink(license) {}

// TODO: Create a function that returns the license section of README
// If there is no license, return an empty string
function renderLicenseSection(license) {}

// TODO: Create a function to generate markdown for README
function generateMarkdown(data) {
  return `
  🏅
  ![badge](https://img.shields.io/badge/license-${data.license})
  🏅<br />
  
  <h1 align="center">${data.projectTitle} </h1>
     
  ## Description
   ${data.description}
  ## Table of Contents
  - [Description](#description)
  - [Installation](#installation)
  - [Purpose](#purpose)
  - [License](#license)
  - [Contributing](#contributing)
  - [Issues](#issues)
  - [Tests](#tests)
  - [Links](#links)
  ## Installation
   ${data.installation}
  ## Purpose
   ${data.purpose}
  ## License
  ![badge](https://img.shields.io/badge/license-${data.license}-tertiary)
  <br />
  This application is covered by the ${data.license} license. 
  ## Contributing
   ${data.contributing}
  ## Issues
 ${data.issues}
  ## Testing
 ${data.testing}
  ## Links
   ${data.links}<br />
  <br />
  :octocat: Find me on GitHub: [${data.username}](https://github.com/${data.username})🧑🏿‍💻<br />
  <br />
   Email me with any questions: ${data.email}<br /><br />
  _README generated by [README-generator](gh/file where posted link)
      `;
}

module.exports = generateMarkdown;
