// TODO: Create a function that returns a license badge based on which license is passed in
// If there is no license, return an empty string
function renderLicenseBadge(license) {}

// TODO: Create a function that returns the license link
// If there is no license, return an empty string
function renderLicenseLink(license) {}

// TODO: Create a function that returns the license section of README
// If there is no license, return an empty string
function renderLicenseSection(license) {}

// TODO: Create a function to generate markdown for README
function generateMarkdown(data) {
  return `
  🏅
  ![badge](https://img.shields.io/badge/license-${answers.license})
  🏅<br />
  
  <h1 align="center">${answers.projectTitle} </h1>
     
  ## Description
   ${answers.description}
  ## Table of Contents
  - [Description](#description)
  - [Installation](#installation)
  - [Purpose](#purpose)
  - [License](#license)
  - [Contributing](#contributing)
  - [Tests](#tests)
  - [Links](#links)
  ## Installation
   ${answers.installation}
  ## Purpose
   ${answers.purpose}
  ## License
  ![badge](https://img.shields.io/badge/license-${answers.license}-tertiary)
  <br />
  This application is covered by the ${answers.license} license. 
  ## Contributing
   ${answers.contributing}
  ## Testing
 ${answers.testing}
  ## Links
   ${answers.links}<br />
  <br />
  :octocat: Find me on GitHub: [${answers.username}](https://github.com/${answers.username})🧑🏿‍💻<br />
  <br />
   Email me with any questions: ${answers.email}<br /><br />
  _README generated by [README-generator](gh/file where posted link)
      `;
}

module.exports = generateMarkdown;
